### ISSUE TITLE
Weapons are invisible

### ISSUE THREAD

**Issue by jellofacey** [Andersso/SM-WeaponModels#1]
Hello, i have an issue with the addon, i already set it all up and configured it to have a custom M4, the one you shown in the video (BF3 m4) 

However any weapon in the game has no viewmodel and if you purchase an M4, the server crashes, related to new update? i hope it gets fixed

**Comment by Andersso** [comment]
Hello,

This project has been stalled for quite a while now, and the logic may or may not have been broken from updates.

But since the plugin uses game-data its likely that some offsets has been outdated and is causing the server crashes.

The vtable offsets are usually easy to fix, but the ones used for accessing unexposed properties in objects requires a little bit more fiddling in IDA.

I'll see if I have some time to test the plugin once again.

**Comment by adigame** [comment]
I was looking for new offset but I not found for StudioHdr, SequenceCount, GetSequenceActivity. 

This plugin would be very handy to us
